### ISSUE TITLE
CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by dsdenes** [mentum/lambdaws#34] opened 2015-01-15 16:56 UTC
// accessKey and secretKey parameters must be provided in the root of the settings object

lambdaws.config({
	accessKey: '',
	secretKey: ''
});

// instead of

lambdaws.config({
	credentials: {
		accessKey: '',
		secretKey: ''
	},
});

**Comment by slvnperron** [comment] 2015-01-15 18:41
Please see lambdaws.js line 64-66

**Comment by slvnperron** [comment] 2015-01-25 19:23
@dsdenes I am closing this issue as we can't reproduce it without your input. Please reopen with appropriate reproduction steps if you are experiencing an issue.

**Closed by slvnperron** 2015-01-25 19:23 UTC
